-- Migration 002: Enrichment Caches
-- Run once in Supabase SQL editor (Dashboard → SQL Editor → New query → Paste → Run)
--
-- Purpose: Cache expensive AI-generated factual content that is student-agnostic.
--          Only factual / program-level data is cached — never student-specific content.
--
-- Golden rule: If two different students looking at the same program get the same
--              content → cache it.  If it changes per student → never cache it.
--
-- Tables added:
--   1. scholarship_cache          — what scholarships/aid exist at a program (by program_id)
--   2. why_this_uni_static_cache  — factual program highlights for Sonnet context (by program_id)
--
-- TTL summary (all caches):
--   program_validation_cache      → 30 days  (was 7 — programs rarely go inactive mid-year)
--   admission_requirements_cache  → 90 days  (was 7 — updated once a year at most)
--   scholarship_cache             → 60 days  (new — scholarships announced quarterly)
--   why_this_uni_static_cache     → 90 days  (new — program facts barely change)

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. Scholarship cache
--    Stores what financial aid OPTIONS exist at a given program.
--    Key: program_id only — NOT nationality or student profile.
--    Student-specific eligibility / filtering is applied at runtime in code,
--    not stored here.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS scholarship_cache (
  id           UUID        DEFAULT gen_random_uuid() PRIMARY KEY,
  program_id   UUID        UNIQUE NOT NULL,
  university_id UUID,                          -- informational
  content      JSONB       NOT NULL,           -- { summary, items: [{name, type, amount, eligibility}] }
  fetched_at   TIMESTAMPTZ DEFAULT NOW(),
  expires_at   TIMESTAMPTZ NOT NULL
);

-- Index for cache reads (eq program_id + gt expires_at)
CREATE INDEX IF NOT EXISTS idx_scholarship_cache_program_expiry
  ON scholarship_cache (program_id, expires_at);

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. Why-this-uni static cache
--    Stores factual program highlights generated by Gemini (with Google Search).
--    These facts are fed as context into the Sonnet personalization prompt.
--    Key: program_id only — never contains student data.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS why_this_uni_static_cache (
  id             UUID        DEFAULT gen_random_uuid() PRIMARY KEY,
  program_id     UUID        UNIQUE NOT NULL,
  university_id  UUID,                          -- informational
  static_block   TEXT        NOT NULL,          -- 3-4 sentences of factual program highlights
  fetched_at     TIMESTAMPTZ DEFAULT NOW(),
  expires_at     TIMESTAMPTZ NOT NULL
);

-- Index for cache reads
CREATE INDEX IF NOT EXISTS idx_why_this_uni_static_cache_program_expiry
  ON why_this_uni_static_cache (program_id, expires_at);
